# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaseTest < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mattnibs/gorelease-test/releases/download/v0.1.0/zed-0.1.0.darwin-arm64.tar.gz"
      sha256 "9f3d5442509b257ec9277ba3a6f43a9a2b0da8526dda2f84ad5f61ecb6348b33"

      def install
        bin.install "releaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattnibs/gorelease-test/releases/download/v0.1.0/zed-0.1.0.darwin-amd64.tar.gz"
      sha256 "4c77c4a779412091b4e2331898ff59b775b7b8707e9bec486258c4f01b5ad8ac"

      def install
        bin.install "releaser"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mattnibs/gorelease-test/releases/download/v0.1.0/zed-0.1.0.linux-arm64.tar.gz"
      sha256 "f0f48a6be2de1ab86bff1e75b5b66fb2572254f7f304fed3463bed0bcf01243d"

      def install
        bin.install "releaser"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mattnibs/gorelease-test/releases/download/v0.1.0/zed-0.1.0.linux-amd64.tar.gz"
      sha256 "92648b5f566c03293efbb04c0dde59d8b0336b0a0a6cbc3bc0f94b31cfa6cf35"

      def install
        bin.install "releaser"
      end
    end
  end
end
